naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'

style:
  MagicNumber:
    active: true
    ignoreAnnotated:
      - 'Test'
    excludes:
      - '**/ui/theme/Color.kt'
      - '**/ui/theme/Theme.kt'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewLightDark'

Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
